language: csharp
mono: none
dotnet: 3.1.403
script:
  - git clone https://github.com/jpd002/PlayServices.git PlayServices
  - pushd PlayServices
  - git checkout develop
  - dotnet run -p tools/CompatibilityValidator
  - popd
